/** 
 * Author   - Calvin Gross and Silas Curtis
 * Date     - 4/22/25
 * Modified - 4/23/25
 * Modified - 4/24/25
 * Title    - Board and Pieces
 * Description - This file defines chess pieces and the chess board in
 *               two different classes. It defines methods centered around 
 *               determining the valid moves for the player whose turn it is.
*/

/**
 * Represents a single chess piece.
 *
 * A Piece stores its type, such as king, queen, rook, bishop, knight, or pawn,
 * along with its color. It also provides helper behavior for displaying the
 * piece and determining the opposing color.
 *
 * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
 */
export class Piece {
    /**
     * Creates a chess piece with a type and color.
     *
     * @param {string} type - The piece type, such as "king", "queen", "rook",
     * "bishop", "knight", or "pawn".
     * @param {number} color - The piece color. Uses 0 and 1 for the two sides.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    constructor(type, color) {
        this.type = type   // "king", "queen", ...
        this.color = color // 0:white  1:black
    }



    /**
     * Returns the opposite color of this piece.
     *
     * @returns {number} The opposite color value.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    opColor() {
        return (this.color + 1) % 2
    }



    /**
     * Returns the Unicode chess symbol for this piece.
     *
     * @returns {string} A Unicode character representing the piece, or "?" if the
     * piece color is invalid.
     *
     * Note: This docstring was generated by ChatGPT.
     *       Additionally, this method was completed by ChatGPT
     */
    display() {
        if (this.color === 1) {
            if (this.type === "king") return "\u2654";
            if (this.type === "queen") return "\u2655";
            if (this.type === "rook") return "\u2656";
            if (this.type === "bishop") return "\u2657";
            if (this.type === "knight") return "\u2658";
            if (this.type === "pawn") return "\u2659";
        } else if (this.color === 0) {
            if (this.type === "king") return "\u265A";
            if (this.type === "queen") return "\u265B";
            if (this.type === "rook") return "\u265C";
            if (this.type === "bishop") return "\u265D";
            if (this.type === "knight") return "\u265E";
            if (this.type === "pawn") return "\u265F";
        } else {
            return "?";
        }
    }
}



/**
 * Represents the full state of a chess board.
 *
 * A Board stores the piece layout, the side to move, en passant state, and
 * castling rights. It also provides methods for displaying the board, checking
 * attacks and check status, generating moves, and applying moves.
 *
 * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
 */
export class Board {
    /**
     * Creates a chess board with piece locations, turn state, en passant data,
     * and castling rights.
     *
     * @param {Array<Array<Piece|null>>} locations - The 8x8 board grid.
     * @param {number} [turn=0] - The side to move.
     * @param {Array<number>} [en_passant=[]] - The en passant target square, if any.
     * @param {boolean} [WLC=true] - Whether white can castle left.
     * @param {boolean} [WRC=true] - Whether white can castle right.
     * @param {boolean} [BLC=true] - Whether black can castle left.
     * @param {boolean} [BRC=true] - Whether black can castle right.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    constructor(locations, turn = 0, en_passant = [], WLC = true, WRC = true, BLC = true, BRC = true) {
        this.locations = locations;
        this.WLC = WLC;               // white left castle
        this.WRC = WRC;               // white right castle
        this.BLC = BLC;               // black left castle
        this.BRC = BRC;               // black right castle
        this.en_passant = en_passant; // pos of skipped square after double pawn move
        this.turn = turn;             // 0:white  1:black
    }



    /**
     * Returns the opposite color of the side whose turn it is.
     *
     * @returns {number} The opposite turn color.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    opColor() {
        return (this.turn + 1) % 2
    }

    /**
     * Determines whether a given square is attacked by an opposing piece.
     *
     * This checks attacks from pawns, knights, kings, rooks, bishops, and queens.
     *
     * @param {Array<number>} square - The square to test as [row, col].
     * @returns {boolean} True if the square is attacked; otherwise false.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    isAttacked(square) {
        let [i, j] = square;
        
        // find pawn denfenders
        let possible_pawn_ck_locs;
        if (this.turn === 0){
            possible_pawn_ck_locs = [[i+1,j-1], [i+1,j+1]];
        }
        else{
            possible_pawn_ck_locs = [[i-1,j-1], [i-1,j+1]];
        }
        for (const [a,b] of possible_pawn_ck_locs) {
            if (a <= 7 && a >= 0 && b <= 7 && b >= 0) {
                let sq = this.locations[a][b];
                if (sq instanceof Piece && sq.type === "pawn" && sq.color === this.opColor()) {
                    return true;
                }
            }
        }       

        // find knight defenders
        let knight_ck_locs = [[i+1,j+2], [i+1,j-2], [i-1,j+2], [i-1,j-2], 
                              [i+2,j+1], [i+2,j-1], [i-2,j+1], [i-2,j-1]];
        // filter out ones not on the board
        // if valid sq check if a opColor knight is on it
        for (const [a,b] of knight_ck_locs) {
            if (a <= 7 && a >= 0 && b <= 7 && b >= 0) {
                let sq = this.locations[a][b];
                if (sq instanceof Piece && sq.type === "knight" && sq.color === this.opColor()) {
                    return true;
                }
            }
        }

        // find straight defenders
        // search up from pos
        let y = 1;
        while (i + y < 8) {
            let sq = this.locations[i+y][j];
            if (!(sq instanceof Piece)) {
                y++;
                continue;
            } 
            // hit piece
            if ((sq.type === "rook" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (y === 1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search down from pos
        y = -1;
        while (i + y >-1) {
            let sq = this.locations[i+y][j];
            if (!(sq instanceof Piece)) {
                y--;
                continue;
            } 
            // hit piece
            if ((sq.type === "rook" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (y === -1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search right from pos
        let x = 1;
        while (j + x < 8) {
            let sq = this.locations[i][j+x];
            if (!(sq instanceof Piece)) {
                x++;
                continue;
            } 
            // hit piece
            if ((sq.type === "rook" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === 1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search left from pos
        x = -1;
        while (j + x > -1) {
            let sq = this.locations[i][j+x];
            if (!(sq instanceof Piece)) {
                x--;
                continue;
            } 
            // hit piece
            if ((sq.type === "rook" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === -1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
    


        // find diagonal defenders
        // search up and right from pos
        y = 1;
        x = 1;
        while (i + y < 8 && j + x < 8) {
            let sq = this.locations[i+y][j+x];
            if (!(sq instanceof Piece)) {
                y++;
                x++;
                continue;
            } 
            // hit piece
            if ((sq.type === "bishop" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === 1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search up and left from pos
        y = 1;
        x = -1;
        while (i + y < 8 && j + x > -1) {
            let sq = this.locations[i+y][j+x];
            if (!(sq instanceof Piece)) {
                y++;
                x--;
                continue;
            } 
            // hit piece
            if ((sq.type === "bishop" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === -1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search down and left from pos
        y = -1;
        x = -1;
        while (i + y > -1 && j + x > -1) {
            let sq = this.locations[i+y][j+x];
            if (!(sq instanceof Piece)) {
                y--;
                x--;
                continue;
            } 
            // hit piece
            if ((sq.type === "bishop" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === -1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }
        // search down and right from pos
        y = -1;
        x = 1;
        while (i + y > -1 && j + x < 8) {
            let sq = this.locations[i+y][j+x];
            if (!(sq instanceof Piece)) {
                y--;
                x++;
                continue;
            } 
            // hit piece
            if ((sq.type === "bishop" || sq.type === "queen") && sq.color === this.opColor()) {
                return true;
            } else if (x === 1 && sq.type === "king" && sq.color === this.opColor()) {
                return true;
            }
            break;
        }

        return false;
    }



    /**
     * Determines whether the current side to move is in check.
     *
     * This finds the current player's king and tests whether its square is attacked.
     *
     * @returns {boolean} True if the current player's king is in check; otherwise false.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    isInCheck() {
        // first find king
        let i = -1; // row
        let j = -1; // col
        let found = false;
        for (const [n, row] of this.locations.entries()) {
            for (const [m, sq] of row.entries()) {
                if (sq instanceof Piece && sq.color === this.turn && sq.type === 'king') {
                    i = n;
                    j = m;
                    found = true;
                    break;
                }
            }
            if (found) {
                break;
            } 
        }

        return this.isAttacked([i,j]);
    }



    /**
     * Finds all pieces of a given type and color on the board.
     *
     * @param {string} pieceType - The piece type to search for.
     * @param {number} pieceColor - The piece color to search for.
     * @returns {Array<Array<number>>} A list of positions in [row, col] form.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    findPieces(pieceType, pieceColor) {
        let positions = [];
        for (const [n, row] of this.locations.entries()) {
            for (const [m, sq] of row.entries()) {
                if (sq instanceof Piece && sq.color === pieceColor && sq.type === pieceType) {
                    positions.push([n,m]);
                }
            }
        }
        return positions;
    }

    /**
     * Moves a piece from one square to another.
     *
     * This also handles rook movement for castling when the king performs a castle move.
     *
     * @param {Array<number>} prevPos - The starting position as [row, col].
     * @param {Array<number>} newPos - The destination position as [row, col].
     *
     * Note: This docstring was generated by ChatGPT.
     */
    makeMove(prevPos, newPos, promotionTo = null) {
        let [a,b] = prevPos;
        let [c,d] = newPos;

        // if castling, move rook too. This was completed using ChatGPT.
        if (this.locations[a][b].type === "king") {
            if (this.WLC && c === 0 && d === 2) {
                this.locations[0][3] = this.locations[0][0];
                this.locations[0][0] = null;
            } else if (this.WRC && c === 0 && d === 6) {
                this.locations[0][5] = this.locations[0][7];
                this.locations[0][7] = null;
            } else if (this.BLC && c === 7 && d === 2) {
                this.locations[7][3] = this.locations[7][0];
                this.locations[7][0] = null;
            } else if (this.BRC && c === 7 && d === 6) {
                this.locations[7][5] = this.locations[7][7];
                this.locations[7][7] = null;
            }
        }
        
        this.locations[c][d] = this.locations[a][b];
        this.locations[a][b] = null;

        // handle promotions
        if ((c === 7 || c === 0) && this.locations[c][d].type === "pawn") {
            this.locations[c][d].type = promotionTo;
        } 

        // if rooks or king moved, remove the respective castling ability
        if (a === 0, b === 4) {
            this.WLC = false;
            this.WRC = false;
        } else if (a === 7, b === 4) {
            this.BLC = false;
            this.BRC = false;
        } else if (a === 0, b === 0) {
            this.WLC = false;
        } else if (a === 0, b === 7) {
            this.WRC = false;
        } else if (a === 7, b === 7) {
            this.BLC = false;
        } else if (a === 7, b === 0) {
            this.BRC = false;
        }
    }



    /**
     * Prints the current board to the terminal using Unicode chess symbols.
     *
     * Empty squares are displayed as blank spaces.
     *
     * Note: This docstring was generated by ChatGPT.
     */
    displayBoardInTerminal() {
        let flipped = this.locations.map(row => row.slice()).slice();
        flipped.reverse();

        for (let [n, row] of flipped.entries()) {
            for (let [m, sq] of row.entries()) {
                if (sq instanceof Piece) flipped[n][m] = sq.display();
                else flipped[n][m] = " ";
            }
        }
        for (const row of flipped) {
            console.log("_______________________________________");
            console.log(" " + row.join("  | "));

        }
        console.log("_______________________________________");
    }



    /**
     * Finds all legal moves for the current player by combining piece-specific move
     * generators and removing moves that leave the king in check.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from starting positions
     * encoded as "row,col" to sets of destination squares in [row, col] form.
     *
     * Note: This docstring was generated by ChatGPT. 
     *       ChatGPT was also used for debugging.
     *       ChatGPT also helped with implimenting new operations
     *       such as: arrow functions, mappings, and the spread operator.
     *          
     */
    findValidMoves() {
        let moves = new Map([
            ...this.findBishopMoves(),
            ...this.findKingMoves(),
            ...this.findKnightMoves(),
            ...this.findPawnMoves(),
            ...this.findQueenMoves(),
            ...this.findRookMoves(),
        ]);

        
        for (const [startPos, moveSet] of moves) {
            for (const endPos of moveSet) {
                let newLocations = this.locations.map(row =>
                    row.map(sq =>
                        sq instanceof Piece ? new Piece(sq.type, sq.color) : null
                    )
                );
                let boardCopy = new Board(
                    newLocations,
                    this.turn,
                    [...this.en_passant],
                    this.WLC,
                    this.WRC,
                    this.BLC,
                    this.BRC
                );
            
            
                boardCopy.makeMove(startPos.split(",").map(Number), endPos.split(",").map(Number));
                if (boardCopy.isInCheck()) {
                    moves.get(startPos).delete(endPos);
                }
            }
        }
        return moves;
    }



    /**
     * Finds all legal knight moves for the current player.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from each knight position
     * encoded as "row,col" to a set of reachable destination squares.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    findKnightMoves() {
        // first search for knights and store their locations in knightsPos
        let knightsPos = this.findPieces("knight", this.turn);
        let knight_moves = new Map();
        
        for (const [y, x] of knightsPos) {
            // create a set in the hashmap of knight_moves for this knight
            // the key must be a str to allow proper referencing, so I use a join
            knight_moves.set([y,x].join(','), new Set());

            let possible_knight_moves;
            possible_knight_moves = [[y+1, x+2], [y-1, x+2], [y+1, x-2], [y-1, x-2], 
                                    [y+2, x+1], [y-2, x+1], [y+2, x-1], [y-2, x-1]];
            
            for (const [n,m] of possible_knight_moves) {
                if (n > -1 && n < 8 && m > -1 && m < 8 && !(this.locations[n][m] instanceof Piece && this.locations[n][m].color === this.turn)) {
                    knight_moves.get([y,x].join(',')).add([n, m].join(','));
                }
            }
        }
        return knight_moves;
    }



    /**
    * Finds all bishop moves for the current player by tracing diagonals until a
    * piece blocks movement or an opposing piece can be captured.
    *
    * @returns {Map<string, Set<Array<number>>>} A map from each bishop position
    * encoded as "row,col" to a set of reachable destination squares.
    *
    * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
    */
    findBishopMoves() {
        // first search for bishops and store their locations in bishopsPos
        let bishopsPos = this.findPieces("bishop", this.turn);
        let bishop_moves = new Map();
        
        for (const [y, x] of bishopsPos) {
            // create a set in the hashmap of bishop_moves for this bishop
            // the key must be a str to allow proper referencing, so I use a join
            bishop_moves.set([y,x].join(','), new Set());


            // find all moves up and right
            let n = 1;
            let w = 1;
            while (n+y < 8 && w+x < 8) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n++;
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves up and left
            n = 1;
            w = -1;
            while (n+y < 8 && w+x > -1) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n++;
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves down and left
            n = -1;
            w = -1;
            while (n+y > -1 && w+x > -1) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n--;
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves down and right
            n = -1;
            w = 1;
            while (n+y > -1 && w+x < 8) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n--;
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    bishop_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
        }
        return bishop_moves;
    }



    /**
     * Finds all rook moves for the current player by tracing horizontal and
     * vertical lines until blocked or a capture is possible.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from each rook position
     * encoded as "row,col" to a set of reachable destination squares.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    findRookMoves() {
        // first search for rooks and store their locations in rooksPos
        let rooksPos = this.findPieces("rook", this.turn);
        let rook_moves = new Map();
        
        for (const [y, x] of rooksPos) {
            // create a set in the hashmap of rook_moves for this rook
            // the key must be a str to allow proper referencing, so I use a join
            rook_moves.set([y,x].join(','), new Set());

            // find all moves up
            let n = 1;
            while (n+y < 8) {
                let sq = this.locations[y+n][x];
                if (!(sq instanceof Piece)) {
                    rook_moves.get([y,x].join(',')).add([y+n, x].join(','));
                    n++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    rook_moves.get([y,x].join(',')).add([y+n, x].join(','));
                }
                break;
            }
            // find all moves down
            n = -1;
            while (n+y > -1) {
                let sq = this.locations[y+n][x];
                if (!(sq instanceof Piece)) {
                    rook_moves.get([y,x].join(',')).add([y+n, x].join(','));
                    n--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    rook_moves.get([y,x].join(',')).add([y+n, x].join(','));
                }
                break;
            }            
            // find all moves right
            let w = 1;
            while (w+x < 8) {
                let sq = this.locations[y][x+w];
                if (!(sq instanceof Piece)) {
                    rook_moves.get([y,x].join(',')).add([y, x+w].join(','));
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    rook_moves.get([y,x].join(',')).add([y, x+w].join(','));
                }
                break;
            }
            // find all moves left
            w = -1;
            while (w+x > -1) {
                let sq = this.locations[y][x+w];
                if (!(sq instanceof Piece)) {
                    rook_moves.get([y,x].join(',')).add([y, x+w].join(','));
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    rook_moves.get([y,x].join(',')).add([y, x+w].join(','));
                }
                break;
            }
        }
        return rook_moves;
    }



    /**
     * Finds all queen moves for the current player by combining rook-like and
     * bishop-like movement.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from the queen position
     * encoded as "row,col" to a set of reachable destination squares.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    findQueenMoves() {
        // first search for the queen and store its pos in queenPos
        let queenPos = this.findPieces("queen", this.turn);
        let queen_moves = new Map();
        
        if (!(queenPos.length === 0)) {
            let [y,x] = queenPos[0];

            queen_moves.set([y,x].join(','), new Set());

            // find all moves up
            let n = 1;
            while (n+y < 8) {
                let sq = this.locations[y+n][x];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x].join(','));
                    n++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x].join(','));
                }
                break;
            }
            // find all moves down
            n = -1;
            while (n+y > -1) {
                let sq = this.locations[y+n][x];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x].join(','));
                    n--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x].join(','));
                }
                break;
            }            
            // find all moves right
            let w = 1;
            while (w+x < 8) {
                let sq = this.locations[y][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y, x+w].join(','));
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y, x+w].join(','));
                }
                break;
            }
            // find all moves left
            w = -1;
            while (w+x > -1) {
                let sq = this.locations[y][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y, x+w].join(','));
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y, x+w].join(','));
                }
                break;
            }

            // find all moves up and right
            n = 1;
            w = 1;
            while (n+y < 8 && w+x < 8) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n++;
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves up and left
            n = 1;
            w = -1;
            while (n+y < 8 && w+x > -1) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n++;
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves down and left
            n = -1;
            w = -1;
            while (n+y > -1 && w+x > -1) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n--;
                    w--;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
            // find all moves down and right
            n = -1;
            w = 1;
            while (n+y > -1 && w+x < 8) {
                let sq = this.locations[y+n][x+w];
                if (!(sq instanceof Piece)) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                    n--;
                    w++;
                    continue;
                } else if (sq.color === this.opColor()) {
                    queen_moves.get([y,x].join(',')).add([y+n, x+w].join(','));
                }
                break;
            }
        }
        return queen_moves;
    }



    /**
     * Finds all pawn moves for the current player, including single-step moves,
     * captures, initial two-square advances, and en passant moves when available.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from each pawn position
     * encoded as "row,col" to a set of reachable destination squares.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    findPawnMoves() {
        let PawnsPos = this.findPieces("pawn", this.turn);
        let pawn_moves = new Map();
        let possible_pawn_moves;
        for (const [y,x] of PawnsPos) {

            pawn_moves.set([y,x].join(','), new Set());

            if (this.turn === 0) {
                possible_pawn_moves = [[y+1,x-1], [y+1,x], [y+1,x+1]];
            } else {
                possible_pawn_moves = [[y-1,x-1], [y-1,x], [y-1,x+1]];
            }
            
            for (const [n,m] of possible_pawn_moves) {
                let sq = this.locations[n][m];
                // check if each pawn can move straight forward
                if (m === x) {
                    if (!(sq instanceof Piece)) {
                        pawn_moves.get([y,x].join(',')).add([n, m].join(','));
                    }
                // check if each pawn can move diagonal
                } else if (sq instanceof Piece && sq.color === this.opColor()) {
                    pawn_moves.get([y,x].join(',')).add([n, m].join(','));
                // check for en passant moves
                } else if (sq === this.en_passant) {
                    pawn_moves.get([y,x].join(',')).add([n, m].join(','));
                }
            }

            // check for 2 sq moves 
            if (this.turn === 0 && y === 1) {
                if (!(this.locations[y+1][x] instanceof Piece) && !(this.locations[y+2][x] instanceof Piece)) {
                    pawn_moves.get([y,x].join(',')).add([y+2, x].join(','));
                }
            } else if (this.turn === 1 && y === 6) {
                if (!(this.locations[y-1][x] instanceof Piece) && !(this.locations[y-2][x] instanceof Piece)) {
                    pawn_moves.get([y,x].join(',')).add([y-2, x].join(','));
                }
            }
        }
        return pawn_moves;
    }



    /**
     * Finds all king moves for the current player, including normal one-square
     * moves and castling when castling rights and safety conditions allow it.
     *
     * @returns {Map<string, Set<Array<number>>>} A map from the king position
     * encoded as "row,col" to a set of reachable destination squares.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    findKingMoves() {
        // first search for the queen and store its pos in queenPos
        let [[y,x]] = this.findPieces("king", this.turn);
        let king_moves = new Map();

        king_moves.set([y,x].join(','), new Set());


        // find regular moves
        let possible_king_moves;
        possible_king_moves = [[y+1, x+1], [y-1, x+1], [y+1, x-1], [y-1, x-1], 
                              [y, x+1], [y, x-1], [y+1, x], [y-1, x]];
        
        for (const [m,n] of possible_king_moves) {

            // if out of bounds skip
            if (m>7 || m<0 || n>7 || n<0) {
                continue;
            }
            let sq = this.locations[m][n];

            if (!(sq instanceof Piece && sq.color === this.turn)) {
                king_moves.get([y,x].join(',')).add([m, n].join(','));
            }
        }

        // check for castling
        if (this.turn === 0) {
            if (this.WLC) {
                // if no pieces inbetween, the squares the king moves 
                // through are safe, and the king is not in check.
                if (!(this.locations[0][1] instanceof Piece) &&
                    !(this.locations[0][2] instanceof Piece) &&
                    !(this.locations[0][3] instanceof Piece) &&
                    !(this.isAttacked([0,2])) &&
                    !(this.isAttacked([0, 3])) &&
                    !(this.isAttacked([0, 4]))) {
                        king_moves.get([y,x].join(',')).add([0, 2].join(','));
                    }
            }
            if (this.WRC) {
            // if no pieces inbetween, the squares the king moves 
            // through are safe, and the king is not in check.
                if (!(this.locations[0][5] instanceof Piece) &&
                    !(this.locations[0][6] instanceof Piece) &&
                    !(this.isAttacked([0, 4])) &&
                    !(this.isAttacked([0, 5])) &&
                    !(this.isAttacked([0, 6]))) {
                        king_moves.get([y,x].join(',')).add([0, 6].join(','));
                    }
            }
        } else {
            if (this.BLC) {
                // if no pieces in between, the squares the king moves
                // through are safe, and the king is not in check.
                if (!(this.locations[7][1] instanceof Piece) &&
                    !(this.locations[7][2] instanceof Piece) &&
                    !(this.locations[7][3] instanceof Piece) &&
                    !(this.isAttacked([7, 2])) &&
                    !(this.isAttacked([7, 3])) &&
                    !(this.isAttacked([7, 4]))) {
                        king_moves.get([y,x].join(',')).add([7, 2].join(','));
                    }
            }
            if (this.BRC) {
                // if no pieces in between, the squares the king moves
                // through are safe, and the king is not in check.
                if (!(this.locations[7][5] instanceof Piece) &&
                    !(this.locations[7][6] instanceof Piece) &&
                    !(this.isAttacked([7, 4])) &&
                    !(this.isAttacked([7, 5])) &&
                    !(this.isAttacked([7, 6]))) {
                        king_moves.get([y,x].join(',')).add([7, 6].join(','));
                    }
            }
        }
        return king_moves;
    }
}

