
import { startingBoard } from "./starting_locations.js";
import { Piece, Board } from "./board.js";
import * as testBd from "./testBoard.js";
import { Game } from "./game.js";


/**
 * Compares two arrays for equality by checking that they have the same
 * length and the same values in the same order.
 *
 * @param {Array} a - The first array.
 * @param {Array} b - The second array.
 * @returns {boolean} True if the arrays are equal in length and contents;
 * otherwise false.
 *
 * Note: This docstring was generated by ChatGPT and the
 * function was completely generated by ChatGPT.
 */
function arraysEqual(a, b) {
    if (a.length !== b.length) return false;

    for (let i = 0; i < a.length; i++) {
        if (a[i] !== b[i]) return false;
    }

    return true;
}


//      Cycle 1, TDD Verify En Passant is saved after 2 square pawn move.
//  After a pawn is moved 2 squares, the square jumped over is saved
//  under this.en_passant until the turn after.
// _______________________________________
//  ♜ | ♞ | ♝ | ♛ | ♚ | ♝ | ♞ | ♜
// _______________________________________
//  ♟ | ♟ | ♟ |    | ♟ | ♟ | ♟ | ♟
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    | ♟ |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//  ♟ | ♟ | ♟ | ♟ | ♟ | ♟ | ♟ | ♟
// _______________________________________
//  ♜ | ♞ | ♝ | ♛ | ♚ | ♝ | ♞ | ♜
// _______________________________________
let en_passant_game_0 = new Game(testBd.enPassantBoard0);
console.log(en_passant_game_0.curBoard.displayBoardInTerminal());
let _returns0 = en_passant_game_0.movePiece([1,2], [3,2]);
console.log(en_passant_game_0.curBoard.displayBoardInTerminal());
if (!arraysEqual(en_passant_game_0.curBoard.en_passant, [])) {
    console.log("Passed En Passant Step 0 Verification."); 
} else {
    console.log("Did Not Pass En Passant Step 0 Verification."); 
}



//      Cycle 2: TDD Verify En Passant, Pawn can Move diagonal for Take
//  This does not include removing the piece getting taken.
// _______________________________________
//  ♜ | ♞ | ♝ | ♛ | ♚ | ♝ | ♞ | ♜
// _______________________________________
//  ♟ | ♟ | ♟ |    | ♟ | ♟ | ♟ | ♟
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    | ♟ |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//  ♟ | ♟ | ♟ | ♟ | ♟ | ♟ | ♟ | ♟
// _______________________________________
//  ♜ | ♞ | ♝ | ♛ | ♚ | ♝ | ♞ | ♜
// _______________________________________
let en_passant_game_1 = new Game(testBd.enPassantBoard1);
console.log(en_passant_game_1.curBoard.displayBoardInTerminal());
let _returns1 = en_passant_game_1.movePiece([1,2], [3,2]);
console.log(en_passant_game_1.curBoard.displayBoardInTerminal());
_returns1 = en_passant_game_1.movePiece([3,3], [2,2]);
console.log(en_passant_game_1.curBoard.displayBoardInTerminal());

if (en_passant_game_1.curBoard.locations[2][2] instanceof Piece && en_passant_game_1.curBoard.locations[2][2].type === "pawn") {
    console.log("Passed En Passant Step 1 Verification."); 
} else {
    console.log("Did Not Pass En Passant Step 1 Verification."); 
}
console.log(en_passant_game_1.curBoard.displayBoardInTerminal());



//      Cycle 3: TDD Verify En Passant, Pawn Removed After an En Passant Take
// Here is what the board currently looks like after an en passant move.
// _______________________________________
//  ♟  | ♟  | ♟  |    | ♟  | ♟  | ♟  | ♟
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    | ♟  |    |    |    |    |  
// _______________________________________
//     |    | ♟  |    |    |    |    |  
// _______________________________________
//  ♟  | ♟  |    | ♟  | ♟  | ♟  | ♟  | ♟
// _______________________________________
//  ♜  | ♞  | ♝  | ♛  | ♚  | ♝  | ♞  | ♜
// _______________________________________

let en_passant_game_2 = new Game(testBd.enPassantBoard2);
console.log(en_passant_game_2.curBoard.displayBoardInTerminal());
let _returns2 = en_passant_game_2.movePiece([1,2], [3,2]);
console.log(en_passant_game_2.curBoard.displayBoardInTerminal());
_returns2 = en_passant_game_2.movePiece([3,3], [2,2]);
console.log(en_passant_game_2.curBoard.displayBoardInTerminal());
if (!(en_passant_game_2.curBoard.locations[3][2] instanceof Piece)) {
    console.log("Passed En Passant Step 2 Verification."); 
} else {
    console.log("Did Not Pass En Passant Step 2 Verification."); 
}
console.log(en_passant_game_2.curBoard.displayBoardInTerminal());




//      TDD Verify 3-Fold Repeation Stalemate
// This test has a game starting from just the starting pos. It then moves
// the same two knights for black and white back and forth. Thus, causing 
// a stalemate via 3-fold repetition. Then the test checks if the game's 
// state is "Stalemate".
let three_fold_game = new Game();
three_fold_game.curBoard.turn = 0;
let _ = three_fold_game.movePiece([0,1], [2,2]);
_ = three_fold_game.movePiece([7,1], [5,2]);
_ = three_fold_game.movePiece([2,2], [0,1]);
_ = three_fold_game.movePiece([5,2], [7,1]);
_ = three_fold_game.movePiece([0,1], [2,2]);
_ = three_fold_game.movePiece([7,1], [5,2]);
_ = three_fold_game.movePiece([2,2], [0,1]);
_ = three_fold_game.movePiece([5,2], [7,1]);
_ = three_fold_game.movePiece([0,1], [2,2]);
_ = three_fold_game.movePiece([7,1], [5,2]);
_ = three_fold_game.movePiece([2,2], [0,1]);
let [_board, state] = three_fold_game.movePiece([5,2], [7,1]);
if (state === "Stalemate, 3-Fold Repitition") {
    console.log("Passed 3-Fold Rep Stalemate Verification.");   
} else {
    console.log("Did not pass 3-Fold Rep Stalemate Verification.");  
}



//      TDD Verify Pawn Promotion
// This starts on whites turn, this verifies that when a white 
// pawn is moved to the 7th rank amd a piece type is inputted,
// the pawn is promoted to that piece.
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    | ♟  |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//  ♚  |    |    |    |    |    |    | ♔
// _______________________________________
testBd.promotionBoard.makeMove([6,5], [7,5], "queen");
if (testBd.promotionBoard.locations[7][5].type === "queen") {
    console.log("Passed Pawn Promotion Verification.");
} else {
    console.log("Did not Pass Pawn Promotion Verification.");
}



//      Verify Knight Moves
// On whites turn they can move their knight to take either of 
// the two black pawns, or to the free square (2,1). 3 of their
// moves are blocked by their pawns, and 2 more are out of bounds.
// This test verifies that there are 3 valid moves, and they are 
// the taking the black pawns, or the open square.
// ChatGPT was used to generate the board and piece locations.
// _______________________________________
//  ♚  |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    | ♔
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    | ♟  |    |    |  
// _______________________________________
//     | ♟  |    |    |    | ♙  |    |  
// _______________________________________
//     |    |    | ♞  |    |    |    |  
// _______________________________________
//     | ♟  |    |    |    | ♙  |    |  
// _______________________________________

let knightMoves = testBd.knightMoveBoard.findValidMoves().get("1,3");
if (knightMoves.size === 3 && knightMoves.has("3,2") && knightMoves.has("2,5") && knightMoves.has("0,5")) {
    console.log("Passed Knight Move Verification.");
} else {
    console.log("Did not pass Knight Move Verification.");
}



//      Verify Bishop Moves
// This starts on blacks turn and extracts the moves generated for 
// the bishop out from findValidMoves. Then it verifies that each move
// exists and no others.
// _______________________________________
//     |    | ♘  |    |    |    |    | ♔
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    | ♗  |    |  
// _______________________________________
//     |    |    |    | ♟  |    |    |  
// _______________________________________
//     |    |    |    |    |    |    | ♞
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//  ♚  |    |    |    |    |    |    |  
// _______________________________________
let bishopMoves = testBd.BishopMoveBoard.findValidMoves().get("4,5");
const bishopCorrectMoves = ["5,6", "6,7", "5,4", "6,3", "3,4", "3,6", "2,7"];
if (bishopMoves.size === 7) {
    for (const corMove of bishopCorrectMoves) {
        if (!bishopMoves.has(corMove)) {
            console.log("Did not pass Bishop Move Verification.");
            break;
        }
    }
    console.log("Passed Bishop Move Verification.");
} else {
    console.log("Did not pass Bishop Move Verification.");
}



//      Verify Queen Moves
// This verifies that the queens moves are correct. I checks 
// that it can't take its own pieces and that it 
// _______________________________________
//  ♙  |    |    |    |    |    |    | ♔
// _______________________________________
//     | ♟  |    |    |    |    |    |  
// _______________________________________
//  ♛  |    |    |    |    |    | ♙  |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    | ♟  |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    |    |    |    |  
// _______________________________________
//     |    |    |    | ♚  |    |    |  
// _______________________________________
let queenMoves = testBd.queenMoveBoard.findValidMoves().get("5,0");
const queenCorrectMoves = ["6,0", "7,0", "5,1", "5,2", "5,3", "5,4", "5,5", 
                           "5,6", "4,1", "4,0", "3,0", "2,0", "1,0", "0,0"];
if (queenMoves.size === 14) {
    for (const corMove of queenCorrectMoves) {
        if (!queenMoves.has(corMove)) {
            console.log("Did not pass Queen Move Verification.");
            break;
        }
    }
    console.log("Passed Queen Move Verification.");
} else {
    console.log("Did not pass Queen Move Verification.");
}



