/** 
 * Author   - Calvin Gross and Silas Curtis
 * Date     - 4/23/25
 * Modified - 4/24/25
 * Title    - The Game
 * Description - This file defines the game class which allows users to play a game of 
 *               chess in the terminal. It also provides methods for interfacing with the
 *               frontend allowing for clean communication.
*/

import { startingBoard } from "./starting_locations.js";
import { Piece, Board } from "./board.js";

// ChatGPT generated, necessary for terminal input
// import readline from "readline";
// const rl = readline.createInterface({
//     input: process.stdin,
//     output: process.stdout
// });
function ask(question) {
    return new Promise(resolve => rl.question(question, resolve));
}


/**
 * Represents a chess game wrapper around a Board instance.
 *
 * This class tracks the current board, game state, cached move data,
 * prior board positions for repetition detection, and provides methods
 * for terminal play, move lookup, board serialization, and move execution.
 *
 * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
 */
export class Game {
    /**
     * Creates a new Game instance.
     *
     * @param {Board} [curBoard=startingBoard] - The initial board state for the game.
     * @param {string} [state="active"] - The current game state, such as "active",
     * "checkmate", or "stalemate".
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    constructor(curBoard = startingBoard, state = "active") {
        this.curBoard = curBoard;
        this.state = state; // "active", "checkmate", "stalemate"
        this.prevBoards = new Map();
        this.prevBoardsCount = 1;
        this.currentMoves = new Map();
    }

    /**
     * Runs the game loop in the terminal using readline input.
     *
     * This method displays the board, gathers legal moves, accepts user input,
     * validates moves, handles promotions, updates the board, and ends when the
     * game reaches checkmate or stalemate.
     *
     * @returns {Promise<void>} Resolves when terminal play ends.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    async playTerminalGame() {
        while (this.state === "active") {
            // display board
            this.board.displayBoardInTerminal();


            // get valid moves
            let no_moves = true;
            let moves = new Map();
            moves = this.board.findValidMoves()

            // if no moves determine outcome and end the game
            for (const [startPos, endSet] of moves) {
                if (!(endSet.size === 0)) {
                    no_moves = false;
                    break;
                }
            }

            if (no_moves && this.board.isInCheck()) {
                if (this.board.turn === 0) {
                    console.log("Black Wins by Checkmate!");
                } else {
                    console.log("White Wins by Checkmate!");
                }
                this.state = "checkmate";
                break;
            }   else if (no_moves) {
                console.log("Stalemate, no one wins.");
                this.state = "stalemate";
                break;
            }   

            let move_invalid = true;
            // input move, loop until valid
            while (move_invalid) {
                let startInput = await ask("Enter location of piece you are moving (row,col): ");
                let endInput = await ask("Enter location of where you put it (row,col): ");

                if (startInput === "show moves") {
                    console.log(moves);
                }

                
                // validate move
                if (moves.has(startInput) && moves.get(startInput).has(endInput)) {
                    move_invalid = false;

                    startInput = startInput.split(",").map(Number);
                    endInput = endInput.split(",").map(Number);


                    let promotion = null;
                    const valid_promotions = new Set(["knight", "rook", "bishop", "queen"]);
                    let invalid_promotion = true;
                    if ((endInput[0] === 7 || endInput[0] === 0) && this.board.locations[startInput[0]][startInput[1]].type === "pawn") {
                        while (invalid_promotion) {
                            promotion = await ask("What do you want to promote to?: ")
                            console.log(promotion);
                            if (valid_promotions.has(promotion)) {
                                invalid_promotion = false;
                            }
                        }
                    }


                    if (promotion === null) {
                        this.board.makeMove(startInput, endInput)
                    } else {
                        // make move
                        this.board.makeMove(startInput, endInput, promotion);
                    }
                }
            }
            
            // switch to next player
            this.board.turn = this.board.opColor();
        }
    }

    /**
     * Returns the currently available moves for the piece on a given square.
     *
     * If cached moves are empty, this method refreshes them from the current board.
     * Returned moves are converted from "row,col" strings into numeric coordinate pairs.
     *
     * @param {Array<number>} square - The square to inspect in [row, col] form.
     * @returns {Set<Array<number>>} A set of legal destination squares as [row, col] arrays.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    getMovesFromSquare(square) {

        if (this.currentMoves.size === 0) {
            this.currentMoves = this.curBoard.findValidMoves();
        }

        const [y,x] = square;
        const squareKey = y+","+x;
        let moves = new Set();
        if (this.curBoard.locations[y][x] instanceof Piece) {
            moves = this.currentMoves.get(squareKey);
        }
        let unconcatMoves = new Set();
        for (let move of moves) {
            unconcatMoves.add(move.split(",").map(Number));
        }
        return unconcatMoves;
    }

    /**
     * Counts the number of pieces currently on the board.
     *
     * @returns {number} The total number of non-empty squares containing Piece objects.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    piecesLeftCount() {
        let count = 0;
        for (const row of this.curBoard.locations) {
            for (const sq of row) {
                if (sq instanceof Piece) {
                    count++;
                }
            }
        }
        return count;
    }

    /**
     * Serializes the current board into a flat string representation.
     *
     * Empty squares are represented by spaces, while occupied squares are represented
     * by the piece type followed by its color value. This is used for repetition tracking.
     *
     * @returns {string} A string representation of the board state.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    boardStr() {
        let boardStr = [];

        for (const row of this.curBoard.locations) {
            for (const sq of row) {
                if (sq === null) boardStr.push(" ");
                else boardStr.push(sq.type + sq.color);
            }
        }
        return boardStr.join("");
    }

    /**
     * Applies a move to the current board and updates game state.
     *
     * This method performs the move, updates turn state, refreshes valid moves,
     * checks for checkmate or stalemate, and tracks repetition and 50-move-rule
     * conditions.
     *
     * @param {Array<number>} start - The starting square in [row, col] form.
     * @param {Array<number>} end - The destination square in [row, col] form.
     * @param {string|null} [promoteTo=null] - The piece type to promote a pawn to, if applicable.
     * @returns {[Board, string]} The updated board and the current game state.
     *
     * Note: This docstring was generated by ChatGPT. ChatGPT was also used for debugging.
     */
    movePiece(start, end, promoteTo = null) {
        // start and end are in form [1,2] not strings


        // verify that this is a legal move.
        if (this.currentMoves.size === 0) {
            this.currentMoves = this.curBoard.findValidMoves();
        }
        let valid_moves = this.getMovesFromSquare(start);
        let isValid = false;
        for (let m of valid_moves) {
            if (m[0] === end[0] && m[1] === end[1]) {
                isValid = true;
                break;
            }
        }
        if (!isValid) {
            console.log("invalid move");
            return [this.curBoard, this.state];
        }

        let noMoves = true
        const pieceCountBefore = this.piecesLeftCount();

        this.curBoard.makeMove(start, end, promoteTo);
        this.curBoard.turn = this.curBoard.opColor();
        
        
        this.currentMoves = this.curBoard.findValidMoves();
        console.log(this.currentMoves)
        const values = [...this.currentMoves.values()];
        for (let i = 0; i < values.length; i++) {
            if (values[i].size !== 0) {
                noMoves = false;
                break;
            }
        }
        // check for stalemate or checkmate
        if (noMoves) {
            if (this.curBoard.isInCheck()) {
                if (this.curBoard.turn === 0) {
                    this.state = "Black Wins by Checkmate";
                } else {
                    this.state = "White Wins by Checkmate";
                }
            }   else {
                this.state = "Stalemate, No Available Moves";
            }
        }

        // check for 3-fold rep or 50 move rule
        if (this.state === "active") {

            // detect pawn move or piece take and reset prevBoards and count
            const pieceCountAfter = this.piecesLeftCount();
            if (this.curBoard.locations[end[0]][end[1]].type === "pawn" || pieceCountBefore !== pieceCountAfter) {
                this.prevBoards = new Map();
                this.prevBoardsCount = 0;
            }

            // add current to prevBoards map
            if (this.prevBoards.has(this.boardStr())) {
                this.prevBoards.set(this.boardStr(), this.prevBoards.get(this.boardStr()) + 1);
            } else this.prevBoards.set(this.boardStr(), 1);
            this.prevBoardsCount++;

            // change state if needed
            if (this.prevBoards.get(this.boardStr()) === 3) {
                this.state = "Stalemate, 3-Fold Repitition";
            } else if (this.prevBoardsCount >= 50) {
                this.state = "Stalemate, 50 Move Rule";
            }
        }

        // will return board
        // will return state
        return [this.curBoard, this.state];
    }

}