/** 
 * Author   - Calvin Gross
 * Date     - 4/23/25
 * Title    - The starting_locations
 * Description - This file defines the starting locations of each piece. startingBoard was
 *               generated by ChatGPT.
*/

import { Piece, Board } from "./board.js";

export let startingBoard = new Board([
    [
        new Piece("rook", 0),
        new Piece("knight", 0),
        new Piece("bishop", 0),
        new Piece("queen", 0),
        new Piece("king", 0),
        new Piece("bishop", 0),
        new Piece("knight", 0),
        new Piece("rook", 0)
    ],
    [
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0),
        new Piece("pawn", 0)
    ],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1),
        new Piece("pawn", 1)
    ],
    [
        new Piece("rook", 1),
        new Piece("knight", 1),
        new Piece("bishop", 1),
        new Piece("queen", 1),
        new Piece("king", 1),
        new Piece("bishop", 1),
        new Piece("knight", 1),
        new Piece("rook", 1)
    ]], 0, [], true, true, true, true);

export let promotionBoard = new Board([
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, new Piece("pawn", 0), null, null],
    [new Piece("king", 0), null, null, null, null, null, null, new Piece("king", 1)]
], 0, [], false, false, false, false);
